name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  Building:
    name: Compile source code
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        node_version: [12, 14]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
      - name: Restore CI Cache
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ matrix.node_version }}-${{ hashFiles(matrix.os == 'windows-latest' && '**\yarn.lock' || '**/yarn.lock') }}
      - name: Install Dependencies
        run: yarn --frozen-lockfile
      - name: Compile Projects
        run: yarn build
